apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: appuser
  POSTGRES_PASSWORD: apppass
  POSTGRES_DB: shopdb
  DATABASE_URL: postgresql://appuser:apppass@postgres:5432/shopdb
